env:
  COMPOSE_VERSION: 1.7.1
  DOCKER_VERSION: 1.11.2

language: python

branches:
  except:
    - gh-pages

python:
  - "2.7"

virtualenv:
  system_site_packages: true

sudo: required

services:
  - docker

before_install:
 - docker --version
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - sudo apt-get install python-libtorrent -y
 - docker-compose -f tests/test-env/docker-compose.yml up -d

install:
  - pip install ipgetter sleekxmpp flask flask-jsonrpc netifaces humanize coveralls

script:
  - coverage run setup.py test

after_success:
  coveralls