env:
  COMPOSE_VERSION: 1.7.1
  DOCKER_VERSION: 1.11.2

language: python

branches:
  except:
    - gh-pages

python:
  - "2.7"

virtualenv:
  system_site_packages: true

sudo: required

services:
  #- docker

before_install:
 - sudo apt-get update
 - sudo apt-get -o Dpkg::Options::="--force-confdef"  -y --force-yes install docker-engine python-libtorrent
 #- docker --version
 #- curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 #- chmod +x docker-compose
 #- sudo mv docker-compose /usr/local/bin
 #- docker-compose -f tests/test-env/docker-compose.yml up --force-recreate -d

install:
  - pip install -r requirements.txt
  - pip install coverage

script:
  - coverage run setup.py test

after_success:
  coveralls