language: python

branches:
  except:
    - gh-pages

python:
  - "2.7"

before_install:
  - sudo apt-get install python-libtorrent

install:
  - pip install ipgetter sleekxmpp flask flask-jsonrpc netifaces humanize

script:
  - python setup.py test

after_success:
  coveralls